"""Proof that the release bundle is generated by TanStack Start SPA mode."""

from __future__ import annotations

import os
import re
import socket
import subprocess
from pathlib import Path

import pytest


def test_production_build_generates_packagable_tanstack_spa_shell() -> None:
    try:
        with socket.socket() as listener:
            listener.bind(("127.0.0.1", 0))
    except PermissionError:
        pytest.skip("real TanStack SPA build requires a loopback preview socket")

    repository = Path(__file__).parents[2]
    ui = repository / "ui"
    secret_marker = "packaged-ui-test-secret-marker"
    subprocess.run(
        ["npm", "run", "build"],
        cwd=ui,
        env={
            **os.environ,
            "ORION_API_KEY": secret_marker,
            "ORION_TEST_SECRET_MARKER": secret_marker,
        },
        check=True,
    )

    client = ui / "dist" / "client"
    shell = client / "_shell.html"
    assert shell.is_file()
    assert not (client / "index.html").exists()
    assert not (ui / "scripts" / "write-static-shell.mjs").exists()

    html = shell.read_text(encoding="utf-8")
    stylesheet = _asset_reference(html, r"/assets/styles-[^\"]+\.css")
    entrypoint = _asset_reference(html, r"/assets/index-[^\"]+\.js")
    assert (client / stylesheet.removeprefix("/")).is_file()
    assert (client / entrypoint.removeprefix("/")).is_file()
    assert "grain" in (client / stylesheet.removeprefix("/")).read_text(encoding="utf-8")
    assert secret_marker not in _packaged_text(client)


def _asset_reference(html: str, pattern: str) -> str:
    match = re.search(pattern, html)
    assert match is not None, f"SPA shell did not reference generated asset matching {pattern}"
    return match.group(0)


def _packaged_text(directory: Path) -> str:
    return "\n".join(
        path.read_text(encoding="utf-8", errors="ignore")
        for path in directory.rglob("*")
        if path.is_file()
    )
