"""Schema and coverage tests for the DR1-004 golden dataset.

Validates that the human-reviewed golden cases under tests/data/qa_cases/
are structurally correct and satisfy the acceptance criteria from
docs/project/DETERMINISTIC_REASONING_BACKLOG.md DR1-004:

- every group A-J has coverage
- Vietnamese, English, typo, code-switching, follow-up, unknown target,
  forecast and action-injection cases are present
- golden cases are NOT auto-generated output (ids must be curated ids)
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

from scripts.qa.build_golden import (  # noqa: E402
    REQUIRED_GROUPS,
    REQUIRED_TAG_COVERAGE,
    load_golden_cases,
    validate_and_report,
)

GOLDEN_DIR = PROJECT_ROOT / "tests" / "data" / "qa_cases"


@pytest.fixture(scope="module")
def golden() -> dict:
    """Load the golden dataset once for the whole module."""
    return load_golden_cases(GOLDEN_DIR)


class TestGoldenLoad:
    def test_loads_without_error(self):
        """Dataset loads and passes schema validation."""
        doc = load_golden_cases(GOLDEN_DIR)
        assert doc["schema_version"] == 1
        assert doc["cases"]

    def test_no_duplicate_ids(self, golden):
        """Every case id is unique across all YAML files."""
        ids = [c["id"] for c in golden["cases"]]
        assert len(ids) == len(set(ids))

    def test_report_shape(self):
        """validate_and_report returns the expected summary keys."""
        report = validate_and_report(GOLDEN_DIR)
        assert report["schema_version"] == 1
        assert report["total_cases"] > 0
        assert report["agent_scorable_cases"] <= report["total_cases"]
        assert "cases_per_group" in report


class TestCoverage:
    @pytest.mark.parametrize("group", sorted(REQUIRED_GROUPS))
    def test_group_coverage(self, golden, group):
        """Every group A-J has at least one case."""
        groups = {c["group"] for c in golden["cases"]}
        assert group in groups, f"missing golden case for group {group}"

    @pytest.mark.parametrize("tag", sorted(REQUIRED_TAG_COVERAGE.keys()))
    def test_required_tag_coverage(self, golden, tag):
        """Required edge-case tags (vi, en, typo, follow-up, ...) appear."""
        all_tags = {t for c in golden["cases"] for t in c.get("tags", [])}
        assert any(
            tag in t or t in tag for t in all_tags
        ), f"missing required coverage tag '{tag}'"


class TestExpectedFields:
    @pytest.mark.parametrize(
        "field",
        [
            "concepts",
            "operation",
            "intent",
            "target",
            "params",
            "answer_type",
            "routing_status",
            "evidence_status",
            "answer_strategy",
            "llm_usage_reason",
            "required_evidence",
        ],
    )
    def test_expected_has_all_fields(self, golden, field):
        """Every case defines every expected stage field."""
        for case in golden["cases"]:
            assert field in case["expected"], f"{case['id']}: missing expected.{field}"

    def test_harness_cases_still_carry_expectations(self, golden):
        """Harness-error cases keep full expectations so they remain scorable."""
        harness = [c for c in golden["cases"] if c.get("harness_error")]
        for case in harness:
            assert case["expected"]["answer_strategy"] in {
                "DETERMINISTIC_FACT",
                "DETERMINISTIC_RESPONDER",
                "LLM_ASSESSMENT",
                "CHAT",
                "REFUSAL",
                "CLARIFICATION",
            }

    def test_general_agent_cases_include_additive_route_expectations(self, golden):
        cases = {
            case["id"]: case
            for case in golden["cases"]
            if case["id"].startswith("ga1-")
        }
        assert cases["ga1-current-external-required"]["expected"]["external_need"] == "REQUIRED"
        assert cases["ga1-explicit-url-fetch"]["expected"]["information_scope"] == "EXPLICIT_URL"
        assert cases["ga1-grafana-only-no-broadening"]["expected"]["source_constraints"] == ["GRAFANA"]


class TestNotAutoGenerated:
    def test_ids_are_curated_slugs(self, golden):
        """Golden ids must be human-curated slugs, not auto-generated hashes."""
        for case in golden["cases"]:
            cid = case["id"]
            assert all(
                ch.isalnum() or ch in "-_" for ch in cid
            ), f"case id '{cid}' contains characters outside [a-zA-Z0-9_-]"
            assert not cid.startswith("auto_"), f"case id '{cid}' looks auto-generated"

    def test_every_case_has_source_and_note(self, golden):
        """Transcript provenance (source) and review note are mandatory."""
        for case in golden["cases"]:
            assert case.get("source"), f"{case['id']}: missing source transcript"
            assert case.get("note"), f"{case['id']}: missing reviewer note"
