from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class ExecutionStep:
    """
    Immutable execution step generated by the reasoning model.
    """

    step_type: str
    payload: object
