from __future__ import annotations

from dataclasses import dataclass

from .execution_step import ExecutionStep


@dataclass(frozen=True, slots=True)
class ExecutionPlan:
    """
    Immutable execution plan generated by the reasoning model.
    """

    steps: tuple[ExecutionStep, ...]
